// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by editing the '
          'lib/firebase_options.dart file.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by editing the '
          'lib/firebase_options.dart file.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by editing the '
          'lib/firebase_options.dart file.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by editing the '
          'lib/firebase_options.dart file.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKkjmvQ9EMYHru9bbO1bADhGx69rZwdfg',
    appId: '1:199429585160:web:919155f8d921ab0790d4bd',
    messagingSenderId: '199429585160',
    projectId: 'mrwaterprov1-54c3f',
    authDomain: 'mrwaterprov1-54c3f.firebaseapp.com',
    databaseURL: 'https://mrwaterprov1-54c3f-default-rtdb.firebaseio.com',
    storageBucket: 'mrwaterprov1-54c3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArDnXqUojZJVBUAcnW_QWIH3h57nBE6Ic',
    appId: '1:199429585160:android:de08ce0929fc6f6190d4bd',
    messagingSenderId: '199429585160',
    projectId: 'mrwaterprov1-54c3f',
    databaseURL: 'https://mrwaterprov1-54c3f-default-rtdb.firebaseio.com',
    storageBucket: 'mrwaterprov1-54c3f.firebasestorage.app',
  );
}
